### ISSUE TITLE
Errors when doing single particle processing of 2d crystal

### ISSUE THREAD

**Issue by EthanJUCB** [C-CINA/focus#189]
Hi all,

I am trying to extract boxes from one micrograph. It worked perfectly when I extracted boxes for Relion in the absence of phase flipping. 
However, It didn't work when I checked the box "save as phase flipped stack" or "save as CTF-multiplied stack"or "save as  Weiner filtered stack" and got errors as attached.

The other settings were"SPR_whichhalfset=crystalbased" "SPR_whichtiltgeometry=defocus" "SPR"whichCTF=Particle". 

I also wonder if the boxes are extraced from unbent image or the raw image.  Any suggestion will be appreciated. Many thanks

<error>Traceback_** (most recent call last):
  File "/opt/focus/scripts/proc/SPR_ExtractParticles.py", line 1100, in <module>
    main()
  File "/opt/focus/scripts/proc/SPR_ExtractParticles.py", line 480, in main
    boxctfcor = CTF.CorrectCTF( box, DF1=RLDEF1, DF2=RLDEF2, AST=params['AST_ANGLE'], WGH=ampcontrast, apix=apix, Cs=microscope_cs, kV=microscope_voltage, phase_flip=True, return_ctf=False, invert_contrast=False )[0]
  File "/opt/focus/scripts/proc/focus_ctf.py", line 102, in CorrectCTF
    CTFim = -CTF( img.shape, DF1, DF2, AST, WGH, Cs, kV, apix, 0.0, rfft )
  File "/opt/focus/scripts/proc/focus_ctf.py", line 54, in CTF
    ymesh = np.fft.rfftfreq( imsize[1] )
AttributeError: 'module' object has no attribute 'rfftfreq'
</error>[1]    Exit 1                        /usr/bin/python /opt/focus/scripts/proc/SPR_ExtractParticles.py ../ SPR/2dx_merge_dirfile-unique.dat SPR/picking/ SPR/stacks/ particles 100 0.0,360 0.87 300.0 2.6 0.9975 58000 0 y y n y n n 0.4 1.0 0.90 Defocus Particle y y 1 1
Now organizing and converting partial stack(s) to single .mrcs and .par files...
Done!
Done!
 
 Done!
 
########################ExportParticleStack finished.#########################_**

**Comment by rdrighetto** [comment]
Dear EthanJUCB,

Thanks for your interest in FOCUS! The error you are getting is because you
are using a version of NumPy that does not contain fft.rfftfreq. In my
experience this often happens if your script is using the EMAN2 Python
environment, but can also happen for other reasons. Have you configured
FOCUS to find your EMAN2 installation? If so, you can test whether removing
the path to EMAN2 fixes the problem (Settings >> Software >> EMAN2
installation directory).
Also, you can explicitly check which NumPy the scripts are finding by
inserting the following line in the script SPR_ExtractParticles.py right
after the *def main()* line (double-click on the script filename under
"Dependent Scripts" on the FOCUS GUI to open it in your text editor):

print np.__path__

The unbending CC profile is used to identify the particle positions in the
micrograph, but they are extracted from the unbent images.
Please note that extracting particles from 2D crystals for processing with
RELION and FREALIGN is still an experimental feature, and we are working on
a publication of the method.

Please let me know if it works. I will anyway work on a robust version
checking to avoid this error.


--
Ricardo Diogo Righetto

2017-05-19 0:33 GMT+02:00 EthanJUCB <notifications@github.com>:

**Comment by rdrighetto** [comment]
Single-particle 2D-crystal Python scripts now give an error message if using an old version of NumPy that does not contain numpy.fft.rfftfreq.
