### ISSUE TITLE
export raw file

### ISSUE THREAD

**Issue by Eladbic** [C-CINA/focus#203]
Hi 
FOCUS run great on our system. When we try to export the data it work good for all the process data like the sum image, CTF and so. But for the raw micrograph (.mrc) it output error that the mic. dose not exist and sometime it just quit. The folder the has this error has the raw "gaincorrectedstack.mrcs" file but missing the file with the  project name.

Thanks,
Elad

**Comment by sthennin** [comment]
Hi,
The problem was that the unpacked, large, gain-corrected stack was kept in FASTDISK and by default deleted after the drift-corrected version had been generated.
Then, if the Export script tried to export the stack from before drift-correction, it didn't find that stack.

Now, there is a new switch that allows to decide if that non-drift-corrected stack should be deleted or not. If the stack is not deleted at the end of the MotionCor2 script, then it should be possible to export that very large file. 

But: If you have started with the LZV-compressed TIFF stack from SerialEM, and if MotionCor2 has created the drift-corrected final stack, then the non-drift-corrected stack should not be of much value...

The new version is on GitHub.com now, and should be compiled within an hour or so.

Henning.
