### ISSUE TITLE
EPU images

### ISSUE THREAD

**Issue by aseedb** [C-CINA/focus#205]
What would be the procedure to import gain-corrected MRC stacks from EPU?
The automatic import as well as import from EPU seem not to read parameters from the image headers. In the library table all numerical parameters are 0 or 1 (pixel size). Pixel size and number of frames are yet written in the header. 
I do not know if this is related but then when I try to drift correct with any of the 3 possible programs I am getting an error : 
ERROR: First provide gain-corrected stack as FASTDISK/raw_gaincorrectedstack.mrcs
Note, the images were successfully imported as raw_gaincorrectedstack.mrcs (but in the project folder root, not on FASTDISK)

**Comment by sthennin** [comment]
hi,
You are the first person, using EPU and contacting us. 
If you could send us a few example EPU data (MRC stack and metadata XML files?), then I could adjust the "Import from EPU" script for you.
Please send to Henning.stahlberg@unibas.ch
Thanks,

Henning.

**Comment by aseedb** [comment]
Hi Henning,
OK thanks, I'm sending you this.
Benoit

**Comment by rdrighetto** [comment]
Hi Benoit,

I just pushed an update to Github, the installation packages should be
updated within ~1h or you can build from source.
The "Import Movie from EPU" script now works, tested on the data you sent
us. I'm just not 100% sure if the dose is being computed correctly, so
could you please confirm that the results are as expected (check e.g.
"total_dose") and close this ticket if so?

Best wishes,


--
Ricardo Diogo Righetto

2017-12-04 14:17 GMT+01:00 aseedb <notifications@github.com>:

**Comment by aseedb** [comment]
Hi Ricardo,

Many thanks for your quick update! I tried and it worked. Well it crashed near the end of the procedure because of a python problem but I am sure the problem is on my side (wrong python version sourced) and I did not have time to fix it. I will close the issue when I am sure it goes seemless until the end.

Cheers

**Comment by aseedb** [comment]
Hi Ricardo,
The procedure works fine now, I can confirm it. There is one minor problem: when importing the images, the xml files are moved to the import folder, even if the option to delete the original images is not selected. Wouldn't it make more sense to copy the xml files in this case?
Best

**Comment by rdrighetto** [comment]
Hi Benoit,

Thanks for the feedback, glad to know the script works!
I totally agree that this behavior of moving the .xml files around is not
consistent with the "delete the original images" option in the Import GUI.
However fixing that is not so straightforward as it may require changes in
the Import backend code, and I'm out of the office at the moment so won't
be able to work on this soon.
In the meantime, to get the desired behavior you can double click the
"Import Movie from EPU" script on the FOCUS GUI (when processing an
individual image, e.g. after double-clicking it in the library), it should
open the script in a text editor (otherwise, the path of the script is
scripts/image/import/import_epu.script under your FOCUS installation
directory).
Then just change line 124 from

        \mv -f ${import_rawstack_original:r}.xml .

to

        \cp -f ${import_rawstack_original:r}.xml .

Please note that you may lose this change if you update FOCUS if you don't
backup the modified script.


--
Ricardo Diogo Righetto

2017-12-06 23:29 GMT+01:00 aseedb <notifications@github.com>:

**Comment by aseedb** [comment]
Hi Ricardo, Alright thank you!Cheers Benoît 


Envoyé depuis Yahoo Mail pour iPhone


Le jeudi, décembre 7, 2017, 9:15 AM, Ricardo Righetto <notifications@github.com> a écrit :

Hi Benoit,

Thanks for the feedback, glad to know the script works!
I totally agree that this behavior of moving the .xml files around is not
consistent with the "delete the original images" option in the Import GUI.
However fixing that is not so straightforward as it may require changes in
the Import backend code, and I'm out of the office at the moment so won't
be able to work on this soon.
In the meantime, to get the desired behavior you can double click the
"Import Movie from EPU" script on the FOCUS GUI (when processing an
individual image, e.g. after double-clicking it in the library), it should
open the script in a text editor (otherwise, the path of the script is
scripts/image/import/import_epu.script under your FOCUS installation
directory).
Then just change line 124 from

 \mv -f ${import_rawstack_original:r}.xml .

to

 \cp -f ${import_rawstack_original:r}.xml .

Please note that you may lose this change if you update FOCUS if you don't
backup the modified script.


--
Ricardo Diogo Righetto

2017-12-06 23:29 GMT+01:00 aseedb <notifications@github.com>:
