### ISSUE TITLE
ctfapply.py

### ISSUE THREAD

**Issue by z-watson** [C-CINA/focus#211]
Hello,

I am trying to run ctfapply.py on an image from the command line and I am encountering the issue that the corrected micrograph image file is just an image with undefined pixel values for every pixel. If I use the --save_ctf_2d flag, those additional outputs all look fine. I was wondering if there are any suggestions to fix this. I tried both phase flipping and ctf multiplication, but they both had the same problem.

I also notice that I always get this message when I run it, but thought it was probably unrelated:

No handlers could be found for logger "mrcz.test_mrcz"

Thanks,
Zoe

**Comment by rdrighetto** [comment]
Dear Zoe,

Thanks for reporting this bug. There was a problem due to improper memory
mapping when reading the input MRC file; I also detected a bug regarding
the name of the output file. It has been fixed now. However the way it is
now, if you try to apply the CTF correction on a large MRC stack you may
run out of memory; for single images and small stacks it works fine. Please
note that I recently renamed this script to 'focus.ctfapply'.
You can just pull the latest version from GitHub.

Best wishes,


--
Ricardo Diogo Righetto

2018-01-26 23:05 GMT+01:00 z-watson <notifications@github.com>:
