### ISSUE TITLE
Import movie files from EPU

### ISSUE THREAD

**Issue by JMJB** [C-CINA/focus#212]
Dear Focus Team,
I was wondering how to import movie files located in different subdirectories. EPU usually places the movies in folders named as “…/Image-Disc-1/GridSquare_000001/Data/” consequently data from the 2nd GridSquare chosen  is placed in “…/Image-Disc-1/GridSquare_000002/Data/”. I tried to import the movies using the common placeholder as “*” or “?” but this did not work.

Could you please tell me how I could do this?

Kind regards
Jean-Marc

**Comment by rdrighetto** [comment]
Dear Jean-Marc,

We don't use EPU here so it's hard for me to give you a proper answer. My guess is that it should be possible to configure this in EPU itself in order to have all movies saved in the same folder, but I'm not sure. I'm aware there are other EPU users working with Focus so I assume there is a way around it.
@aseedb would you please share your experience in this matter? Thanks a lot.

**Comment by sthennin** [comment]
Dear Jean-Marc,

Could you please send us a ZIP package with an example file structure, plus some dummy images in them, so that we can have a look and implement an import tool that fits to that? 
One way could be to have all images from one grid square (i.e., directory) be imported into one directory within FOCUS, similarly as different tilt series in the tomography mode are imported into different directories. It may be an easy fix. But having an example file structure including XML files would help.

Thanks,  Henning.

**Comment by JMJB** [comment]
Dear Henning,
please download the project.zip file via this dropbox link.
https://www.dropbox.com/s/8zgszm00kehjr9f/project.zip?dl=0

I inserted no dummy images to provide you with correct "EPU-subdirectories" including movies and the ~.xml files taken on a Falcon 3 camera.

Best wishes
Jean-Marc

**Comment by aseedb** [comment]
Hi Ricardo and Henning,
I didn't come across this problem earlier as my tests were done on a single grid square. Jean-Marc is using the same setup as me BTW ;-) 
Benoit
p.s. I realized that I left the gCTF problem on the side. I am checking it and will report in the appropriate issue.

**Comment by JMJB** [comment]
Dear Henning,
the import works fine. 
Thanks for the fix.
Jean-Marc
