### ISSUE TITLE
cursor jumps to the end of a text box during correction of input

### ISSUE THREAD

**Issue by n1kt0** [C-CINA/focus#223]
when correcting some input in a text box the cursor jumps to the end of that box when you press the first key. this behavior is not noticed when typing in an empty text box because the cursor is already at the end.

**Comment by sthennin** [comment]
This is normal behavior, unfortunately. 
If you want to edit a textfield, please replace the entire string with a new text. 
The reason is that FOCUS tries to save the entries each time a keystroke is made. And then, after saving, the cursor jumps to the end of the string...   I agree that this is annoying, but at least one never looses data.
